apiVersion: apps/v1
kind: Deployment
metadata:
  # deployment name
  name: my-udagram-reverseproxy
  labels:
    app: my-udagram-reverseproxy
spec:
  # number of replicated pods
  replicas: 1
  selector:
    matchLabels:
      app: my-udagram-reverseproxy
  template:
    metadata:
      labels:
        app: my-udagram-reverseproxy
    spec:
      containers:
      # docker image name
      - name: udagram-reverseproxy
        image: abdelrahmansherif/udacity-udagram-reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "250m"
        ports:
        - containerPort: 8082
      restartPolicy: Always
