apiVersion: v1
kind: Service
metadata:
  labels:
    service: my-udagram-reverseproxy
  name: my-udagram-reverseproxy
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    service: my-udagram-reverseproxy
  type: LoadBalancer